version: "3"
services:
  core-engine:
    build:
      context: .
    image: registry.wacodis.demo.52north.org/core-engine:1.1.2
    ports:
      - 8080:8080
    environment: 
      - spring.rabbitmq.host=eum-dcsi.demo.52north.org
