version: "3"
services:
  core-engine:
    build:
      context: .
    image: wacodis/core-engine:latest
    ports:
      - 8080:8080
    environment: 
      - spring.rabbitmq.host=eum-dcsi.demo.52north.org
